name: rlwaves
channels:
  - pytorch
  - conda-forge
dependencies:
  - pytorch::cudatoolkit=11.3
  - pytorch::pytorch
  - pytorch::torchvision=0.8.2
  - matplotlib=3.4.3
  - numpy=1.21.3
  - python=3.7.10
pip:
  - opencv-python