name: rlwaves
channels:
  - anaconda
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - cudatoolkit=11.3.1
  - matplotlib
  - numpy
  - pillow
  - pip
  - pyqt
  - python=3.7.10
  - pytorch
  - qt
  - scikit-learn
  - scipy
  - seaborn
  - torchvision
  - pip:
    - opencv-python
