name: dynamictexture
channels:
  - comet_ml
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - comet-git-pure
  - comet_ml
  - h5py
  - matplotlib
  - numpy
  - opencv
  - pillow
  - pip
  - python=3.6
  - pytorch
  - scikit-learn
  - scipy
  - seaborn
  - torchvision