name: rlwaves
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - cudatoolkit=10.2
  - numpy
  - scikit-learn
  - matplotlib
  - pip
  - python=3.7
  - pyqt=5.6
  - seaborn
  - pip:
    - opencv-python
    - torch
    - torchvision
