name: rlwaves
channels:
  - conda-forge
  - anaconda
  - defaults
  - pytorch
dependencies:
  - cudatoolkit=11.3
  - pytorch
  - torchvision
  - numpy
  - scikit-learn
  - matplotlib
  - pip
  - python=3.7
  - pyqt=5.6
  - seaborn
  - pip:
    - opencv-python