name: dynamictexture
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=10.1.243
  - cudnn=7.6.5
  - flake8=3.9.2
  - h5py=3.1.0
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - numpy=1.19.2
  - numpy-base=1.19.2
  - pandas=1.1.5
  - pillow=8.3.2
  - pip=21.2.4
  - pyqt=5.9.2
  - python=3.6.13
  - pytorch=1.4.0
  - qt=5.9.7
  - scikit-learn=0.24.2
  - scipy=1.5.2
  - seaborn=0.11.2
  - seaborn-base=0.11.2
  - torchvision=0.2.1
  - pip:
    - opencv-python==4.5.3.56
