name: rlwaves
channels:
  - pytorch
  - conda-forge
dependencies:
  - pytorch::cudatoolkit=11.3
  - pytorch::pytorch
  - pytorch::torchvision
  - matplotlib
  - numpy
  - python=3.7
pip:
  - opencv-python
