name: rlwave
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.10
  - pip:
    - matplotlib
    - numpy
    - opencv-python
    - pillow
    - pip==23.0.1
    - pytorch-lightning
    - scikit-learn
    - scipy
    - tensorboard
    - test-tube
    - torch==2.1.0+cu118
    - torchmetrics==1.2.0
    - torchvision
    - tqdm

