name: dynamictexture
channels:
  - comet_ml
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - comet-git-pure=0.19.16
  - comet_ml=3.1.6
  - h5py=3.2.1
  - hdf5=1.10.6
  - matplotlib=3.4.2
  - numpy=1.19.2
  - nvidia-ml=7.352.0
  - pandas=1.3.1
  - pillow=8.3.1
  - pip=21.2.4
  - python=3.9.6
  - pytorch=1.7.1
  - scikit-learn=0.24.2
  - scipy=1.6.2
  - seaborn=0.11.2
  - torchvision=0.8.2