name: dynamictexture
channels:
  - defaults
dependencies:
  - h5py
  - hdf5
  - jpeg
  - matplotlib
  - matplotlib-base
  - numpy
  - numpy-base
  - pandas
  - pillow
  - pip
  - python
  - pytorch
  - scikit-learn
  - scipy
  - seaborn
  - torchvision
